### PR TITLE
fix Nice Journey (for real this time)

### PR DESCRIPTION
**Pull request by MrSeemsGood**
Nice Journey's teleport ability now uses EntityPlayer.ControlsEnabled to prevent using active item, just like Wof recommended. seems to work well

### CODE REVIEW

**Comment by Zamiell** [comment]
in the future please dont close PRs and reopen them, you can simply edit the existing PR without generating all of this spam

**Comment by MrSeemsGood** [comment]
#118 should be fixed with this as well.

**Comment by MrSeemsGood** [comment]
> in the future please dont close PRs and reopen them, you can simply edit the existing PR without generating all of this spam

my bad, thanks for the tip!

**Comment by Zamiell** [comment]
can you destructure the constant so that it matches the format of the other callbacks?

**Comment by MrSeemsGood** [comment]
done!

**Pull request merged**
